### ISSUE TITLE
请问这个是什么原因呢？测试api和结果如图所示。谢谢回答~

### ISSUE THREAD

**Issue by lfzx** [realZhangChi/Vue.WebApi#2]
postman：
![image](https://user-images.githubusercontent.com/34572392/55053834-67e7b400-5098-11e9-88f1-4310a21598bc.png)

结果：
![image](https://user-images.githubusercontent.com/34572392/55053778-3ec72380-5098-11e9-8849-c758b6999031.png)

这是mysql数据库表，其中查询、删除功能正常：
![image](https://user-images.githubusercontent.com/34572392/55054131-974af080-5099-11e9-9fdb-ecc78fd13cfd.png)

注册：
![image](https://user-images.githubusercontent.com/34572392/55054357-8353be80-509a-11e9-9d5d-0e39742f46bf.png)
![image](https://user-images.githubusercontent.com/34572392/55054362-8b136300-509a-11e9-807c-17a568661a3b.png)

如果我使用：https://localhost:5001/api/User/register；这种方式进行注册的话会出现以下情况：
![image](https://user-images.githubusercontent.com/34572392/55062963-f452a080-50b1-11e9-8973-f52e561ab525.png)

![image](https://user-images.githubusercontent.com/34572392/55062940-e3099400-50b1-11e9-8918-f3e14d2aae3f.png)

（我把检查当前创建用户是否已存在的语句删除后，就能注册成功！登录使用：https://localhost:5001/api/User/authenticate，最后也能登录成功）

**Comment by lfzx** [comment]
这是mysql数据库表：
![image](https://user-images.githubusercontent.com/34572392/55054083-65398e80-5099-11e9-92cf-60498978c589.png)

**Comment by realZhangChi** [comment]
请问已经解决了吗，应该不会出现这个问题的。你可以看一下_context.User.Any(predicate)的返回值是什么

**Comment by realZhangChi** [comment]
抱歉，应该是有一个controller是弃用了，但是我忘记删除，使用可以成功的那个controller吧

**Comment by lfzx** [comment]
> 抱歉，应该是有一个controller是弃用了，但是我忘记删除，使用可以成功的那个controller吧
谢谢，但是我觉得这不是controller的问题，就是用linq检查数据库中是否重复项而出现的问题。但是我无法解决。if (_iUserRepository.Any(x => x.Email == user.Email))
                  throw new AppException("Email \"" + user.Email + "\" is already taken");

 public bool Any(Expression<Func<User, bool>> predicate)
        {
            return _context.User.Any(predicate);
        }
